$sources:
  - !pw.io.gdrive.read
    object_id: 1Z8z4craj36ighb8hzUzeM76OOgpUdsKr
    service_user_credentials_file: credentials.json  # Path to your service account credentials JSON file
    file_name_pattern:
      - "*.pdf"  # Specify PDF file type
    object_size_limit: null  # Adjust if necessary (set to null for no limit)
    with_metadata: true
    refresh_interval: 30
    mode: streaming

$embedder: !pw.xpacks.llm.embedders.OpenAIEmbedder
  model: "text-embedding-ada-002"
  cache_strategy: !pw.udfs.DefaultCache

$parser: !pw.xpacks.llm.parsers.OpenParse
  cache_strategy: !pw.udfs.DefaultCache
  table_args:
    parsing_algorithm: "llm"
    prompt: pw.xpacks.llm.prompts.DEFAULT_MD_TABLE_PARSE_PROMPT
  image_args:
    parsing_algorithm: "llm"
    prompt: pw.xpacks.llm.prompts.DEFAULT_IMAGE_PARSE_PROMPT

$document_store: !pw.xpacks.llm.document_store.DocumentStore
  docs: $sources
  parser: $parser
  retriever_factory: $retriever_factory

question_answerer: !pw.xpacks.llm.question_answering.BaseRAGQuestionAnswerer
  indexer: $document_store
